package testapp;
// Generated Nov 23, 2018 6:16:24 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Employees generated by hbm2java
 */
@Entity
@Table(name="employees"
    ,catalog="testdb"
)
public class Employees  implements java.io.Serializable {


     private Integer employeeId;
     private String employeeName;
     private String employeeLocation;
     private double employeeSalary;
     private Date rcreTime;

    public Employees() {
    }

    public Employees(String employeeName, String employeeLocation, double employeeSalary, Date rcreTime) {
       this.employeeName = employeeName;
       this.employeeLocation = employeeLocation;
       this.employeeSalary = employeeSalary;
       this.rcreTime = rcreTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="employee_id", unique=true, nullable=false)
    public Integer getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    
    @Column(name="employee_name", nullable=false, length=50)
    public String getEmployeeName() {
        return this.employeeName;
    }
    
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName;
    }

    
    @Column(name="employee_location", nullable=false, length=50)
    public String getEmployeeLocation() {
        return this.employeeLocation;
    }
    
    public void setEmployeeLocation(String employeeLocation) {
        this.employeeLocation = employeeLocation;
    }

    
    @Column(name="employee_salary", nullable=false, precision=22, scale=0)
    public double getEmployeeSalary() {
        return this.employeeSalary;
    }
    
    public void setEmployeeSalary(double employeeSalary) {
        this.employeeSalary = employeeSalary;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="rcre_time", nullable=false, length=10)
    public Date getRcreTime() {
        return this.rcreTime;
    }
    
    public void setRcreTime(Date rcreTime) {
        this.rcreTime = rcreTime;
    }




}


